services:
  detect_camera_angle:
    image: detect_camera_angle:v1.0
    volumes:
      - /tmp/omo-project/:/app
      - /run/user/1000/gvfs/smb-share:server=192.168.104.252,share=omo/CMS_data/record/:/app
    command: python detect_camera_angle.py
    # 使用默認的網絡設置
    # 使用默認的重啟策略
    # 使用默認的環境變量
    # 使用默認的容器名稱