# 使用最新版本的Alpine作為基礎映像
FROM alpine:latest

# 更新APK相關套件並安裝必要的依賴
RUN apk update && apk upgrade && \
    apk add --no-cache python3 py3-pip git

# 下載LightGlue源碼
RUN git clone https://github.com/solaxie/LightGlue.git /app/LightGlue

# 設置工作目錄
WORKDIR /app/LightGlue

# 安裝Python依賴
RUN pip3 install --no-cache-dir -r requirements.txt

# 複製detect_camera_angle.py和send_email.py到工作目錄
COPY detect_camera_angle.py send_email.py /app/LightGlue/

# 設置容器的默認命令
CMD ["python3", "detect_camera_angle.py"]